-- Fonlu semasi. Niteliksiz isimler: hedef sema search_path ile secilir.
-- Supabase'de fonlu semasina, testlerde her kosuda acilan gecici semaya kurulur.

CREATE TABLE prices (
    fund_code text NOT NULL,
    date date NOT NULL,
    kind text,
    fund_name text,
    price double precision,
    shares_outstanding double precision,
    investor_count integer,
    portfolio_size double precision,
    PRIMARY KEY (fund_code, date)
);
CREATE INDEX prices_date ON prices(date);

-- Fon basina yalnizca en guncel anlik goruntu tutuluyor; allocation sifir
-- olmayan pct sutunlarinin JSON haritasi.
CREATE TABLE breakdown (
    fund_code text PRIMARY KEY,
    date date NOT NULL,
    allocation jsonb NOT NULL
);

-- publish_date metin: KAP'tan ham geliyor, siralanip [:10] ile kesiliyor.
CREATE TABLE kap_disclosures (
    disclosure_index bigint PRIMARY KEY,
    fund_code text NOT NULL,
    publish_date text NOT NULL,
    title text,
    subject text,
    summary text,
    disclosure_class text,
    attachment_count integer
);
CREATE INDEX kap_fund ON kap_disclosures(fund_code, publish_date DESC);

-- KAP portfoy dagilim raporundan cikarilan kalemler. Rapor tarihi PK'da:
-- ay bazli kiyas icin fon basina birden fazla rapor tutuluyor.
CREATE TABLE holdings (
    fund_code text NOT NULL,
    report_date date NOT NULL,
    section text NOT NULL,
    code text NOT NULL,
    isin text,
    issuer text,
    value double precision,
    weight_pct double precision,
    disclosure_index bigint,
    PRIMARY KEY (fund_code, report_date, section, code)
);

-- Rozetteki sayimlar. Gunde bir kez, senkron sonunda yazilir: COUNT(DISTINCT
-- fund_code) uretimde 16 saniye suruyor ve bu sayilar yalnizca senkron
-- kostugunda degisiyor, yani her istekte hesaplamak saf israf.
-- Tek satir: id her zaman true, CHECK ikinci satiri engelliyor.
-- last_date bilerek burada YOK: onu arayuz donem alanlarini kurmak icin
-- kullaniyor, bayat bir deger orada gercek bir hataya donusur. MAX(date)
-- zaten index'ten 3 ms'de geliyor.
CREATE TABLE cache_stats (
    id boolean PRIMARY KEY DEFAULT true CHECK (id),
    price_rows bigint NOT NULL,
    fund_count integer NOT NULL,
    kap_count bigint NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE watchlist (
    user_id uuid NOT NULL,
    fund_code text NOT NULL,
    added_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, fund_code)
);

CREATE TABLE positions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    fund_code text NOT NULL,
    units double precision NOT NULL CHECK (units > 0),
    buy_date date NOT NULL,
    buy_price double precision NOT NULL CHECK (buy_price > 0),
    note text
);
CREATE INDEX positions_user ON positions(user_id);
